id: IFF3A5938
legacy_id: P000729
ocr_import_info:
  bdrc_scan_id: W2CZ5019
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T03:02:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:55:28.577971+00:00'
last_modified: 2022-09-02 22:55:48.886921
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ5019
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ5019
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫ་དཔལ་སྤྲུལ་གྱི་རྣམ་ཐར་དད་པའི་གསོས་སྨན་བདུད་རྩིའི་བུམ་བཅུད།
  author: མཁན་པོ་ཀུན་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.5308580866441782
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I00KG010185:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG010185
      total_pages: 138
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG010185.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5308580866441782
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
