id: IFF3A5938
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T03:03:33+00:00'
last_modified: '2022-06-07T13:34:59.769315+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ5019
  title: རྫ་དཔལ་སྤྲུལ་གྱི་རྣམ་ཐར་དད་པའི་གསོས་སྨན་བདུད་རྩིའི་བུམ་བཅུད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9B54:
      image_group_id: I00KG010185
      title: ''
      total_pages: 138
      order: 1
      base_file: 9B54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
