id: P000729
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2CZ5019
  title: རྫ་དཔལ་སྤྲུལ་གྱི་རྣམ་ཐར་དད་པའི་གསོས་སྨན་བདུད་རྩིའི་བུམ་བཅུད
  author: ''
  volumes:
    11d2257d9a8642d98dc287ab3268f1ff:
      image_group_id: I00KG010185
      title: ''
      volume_number: 1
      total_pages: 138
      base_file: v001.txt
